title: <p align="center"> Vikas Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vikaskumar-gupta02/">LinkedIn</a> |
  <a href="https://github.com/HackTheAI">GitHub</a>
  
  <br>   
   I am data scientist having 3 year of experience in field of Energy Sector 
   where I worked on Solar Renewables, Generation Thermal Power Plant and Electric Vehicles Charging 
   along with Customer Centric Analytics by implementing Forecasting Model, Anomaly detection, NLP based analytics etc. 
   Eagar to learn new concept in field of AI/ML and operation research 
   to solve complex problem of real world.
  <br>
  </p>



theme: jekyll-theme-minimal
